# version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: knet_env_postgres
    environment:
      POSTGRES_DB: knet_env_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - knet_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d knet_env_db -p 5432"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: ga111o/knet-environment-backend:latest
    container_name: knet_backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: knet_env_db
      
      TEMP_SENSOR_HOST: 10.5.12.221
      TEMP_SENSOR_PORT: 80
      TEMP_SENSOR_PATH: /
      TEMP_COLLECTION_INTERVAL: 30s
      
      SERVER_PORT: 38333
    ports:
      - "38333:38333"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - knet_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:38333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ga111o/knet-environment-frontend:latest
    container_name: knet_frontend
    environment:
      VITE_API_BASE_URL: http://backend:38333
    ports:
      - "3300:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - knet_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  knet_network:
    driver: bridge

# Access URLs after deployment:
# Frontend: http://localhost:3300
# Backend API: http://localhost:38333