# version: '3.8'

# backend
# Database Configuration
# Sensor Configuration
# Server Configuration
# VITE_API_BASE_URL Configuration

services:
  postgres:
    image: postgres:15-alpine
    container_name: knet_env_postgres
    environment:
      POSTGRES_DB: knet_env_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - knet_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d knet_env_db -p 5432"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: knet_backend
    environment:
      # Database configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: knet_env_db
      
      # Sensor configuration
      TEMP_SENSOR_HOST: 10.5.12.221
      TEMP_SENSOR_PORT: 80
      TEMP_SENSOR_PATH: /
      TEMP_COLLECTION_INTERVAL: 30s
      
      # Server configuration
      SERVER_PORT: 38333
    ports:
      - "38333:38333"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - knet_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:38333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:38333
    container_name: knet_frontend
    environment:
      VITE_API_BASE_URL: http://localhost:38333
    ports:
      - "3300:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - knet_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  knet_network:
    driver: bridge 